### ISSUE TITLE
Cannot open the IDE in browser when using docker launching way on Win7

### ISSUE THREAD

**Issue by laralijuan** [codenvy/artik#177]
**Description of problem:**
Cannot open the IDE in browser when choosing the docker launching method on Win7

**ARTIK IDE version:** 
ARTIK IDE binaries: samsung-artik-ide-nightly (2016/10/14)
Docker version: 1.12.0
Java version: 1.8.0_101
Environment details: **Window 7** + Docker toolbox + JDK
Browser:Chrome

**Steps to Reproduce:**
1. Open the win7's cmd console
2. $docker-machine env default 
3. $docker run --rm -t -v /var/run/docker.sock:/var/run/docker.sock -e CHE_DATA_FOLDER={path-to-location} eclipse/che start
   ![docker_run](https://cloud.githubusercontent.com/assets/20897963/19504699/db53c85a-95ee-11e6-928e-1594f93d09a0.PNG)
4. $docker logs -f che-server
   
   > D:\artik_ide\Artik\artik-ide-nightly-1014\artik-ide-1.2.0-SNAPSHOT\bin>docker logs -f che-server
   > ...
   > 2016-10-19 03:17:00,179[main]             [INFO ] [o.a.catalina.startup.Catalina 642]   - **Server startup in 10439 ms**
   > 2016-10-19 03:19:07,364[ted-scheduler-0]  [ERROR] [a.d.WsMasterAnalyticsAddresser 37]   - **Failed to send master analytics**
   > java.net.ConnectException: Operation timed out
   >         at java.net.PlainSocketImpl.socketConnect(Native Method) ~[na:1.8.0_92-internal]
   >         at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:350) ~[na:1.8.0_92-internal]
   >         at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:206) ~[na:1.8.0_92-internal]
   >         at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:188) ~[na:1.8.0_92-internal]
   >         at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392) ~[na:1.8.0_92-internal]
   >         at java.net.Socket.connect(Socket.java:589) ~[na:1.8.0_92-internal]
   >         at sun.security.ssl.SSLSocketImpl.connect(SSLSocketImpl.java:668) ~[na:1.8.0_92-internal]
   >         at sun.security.ssl.BaseSSLSocketImpl.connect(BaseSSLSocketImpl.java:173) ~[na:1.8.0_92-internal]
   >         at sun.net.NetworkClient.doConnect(NetworkClient.java:180) ~[na:1.8.0_92-internal]
   >         at sun.net.www.http.HttpClient.openServer(HttpClient.java:432) ~[na:1.8.0_92-internal]
   >         at sun.net.www.http.HttpClient.openServer(HttpClient.java:527) ~[na:1.8.0_92-internal]
   >         at sun.net.www.protocol.https.HttpsClient.<init>(HttpsClient.java:264) ~[na:1.8.0_92-internal]
   >         at sun.net.www.protocol.https.HttpsClient.New(HttpsClient.java:367) ~[na:1.8.0_92-internal]
   >         at sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.getNewHttpClient(AbstractDelegateHttpsURLConnection.java:191) ~[na:1.8.0_92-internal]
   >         at sun.net.www.protocol.http.HttpURLConnection.plainConnect0(HttpURLConnection.java:1105) ~[na:1.8.0_92-internal]
   >         at sun.net.www.protocol.http.HttpURLConnection.plainConnect(HttpURLConnection.java:999) ~[na:1.8.0_92-internal]
   >         at sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.connect(AbstractDelegateHttpsURLConnection.java:177) ~[na:1.8.0_92-internal]
   >         at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1513) ~[na:1.8.0_92-internal]
   >         at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1441) ~[na:1.8.0_92-internal]
   >         at java.net.HttpURLConnection.getResponseCode(HttpURLConnection.java:480) ~[na:1.8.0_92-internal]
   >         at sun.net.www.protocol.https.HttpsURLConnectionImpl.getResponseCode(HttpsURLConnectionImpl.java:338) ~[na:1.8.0_92-internal]
   >         at org.eclipse.che.api.deploy.WsMasterAnalyticsAddresser.send(WsMasterAnalyticsAddresser.java:35) ~[classes/:4.7.2]
   >         at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:1.8.0_92-internal]
   >         at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[na:1.8.0_92-internal]
   >         at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.8.0_92-internal]
   >         at java.lang.reflect.Method.invoke(Method.java:498) ~[na:1.8.0_92-internal]
   >         at org.eclipse.che.commons.schedule.executor.LoggedRunnable.run(LoggedRunnable.java:53) [che-core-commons-schedule-4.7.2.jar:4.7.2]
   >         at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [na:1.8.0_92-internal]
   >         at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308) [na:1.8.0_92-internal]
   >         at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180) [na:1.8.0_92-internal]
   >         at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294) [na:1.8.0_92-internal]
   >         at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [na:1.8.0_92-internal]
   >         at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [na:1.8.0_92-internal]
   >         at java.lang.Thread.run(Thread.java:745) [na:1.8.0_92-internal]
5. Open http://192.168.99.100:8080 fail in Chrome. Response is **"ERR_EMPTY_RESPONSE"**
6. Open http://localhost:8080 fail in Chrome. Response is **"ERR_CONNECTION_REFUSED"**

@TylerJewell @eivantsov Could you give me the suggestions? Thanks you~

**Comment by TylerJewell** [comment]
Hi @laralijuan - this is a super weird issue.  In looking at the logs, it does seem that Che has booted just fine.  In looking around the internet, the ERR_EMPTY_RESPONSE is an indication of a networking configuration issue on your host machine.  for example: https://www.wiknix.com/solved-err_empty_response-no-data-received/.

Can you provide:
1. What is the IP address and data dump of the configuration of the docker-machine VM?
2. If you destroy the VM from docker machine and create a new one, does the same issue happen?
3. Are there any Chrome browser console error output messages?

I am thinking that there is something about your networking configuration on your windows box combined with vbox VM that is preventing the browser from reaching the server properly.

The error in the docker logs of WsMasterAnalyticsAddresser is a test that the Che server runs to check its connectivity to the outside world. So since you are behind a firewall, it will fail.  But that error is likely unrelated to the browser error you have for `ERR_EMPTY_RESPONSE`.

**Comment by eivantsov** [comment]
@laralijuan 

Can you please try it this way?

`git clone https://github.com/codenvy/artik-ide`
`artik-ide.bat start`

**Comment by laralijuan** [comment]
@eivantsov 
I follow your suggestion and https://eclipse-che.readme.io/docs/samsung-artik-ide-getting-started
there is also errors
![1](https://cloud.githubusercontent.com/assets/20897963/20590689/9ede80e4-b25f-11e6-9838-d01d4f94f49c.PNG)

I check my docker installation, it works well. so does the Bash.
![2](https://cloud.githubusercontent.com/assets/20897963/20590754/f8bce4de-b25f-11e6-8512-1fc846959b5a.PNG)
![3](https://cloud.githubusercontent.com/assets/20897963/20590790/2100429c-b260-11e6-899e-3dc904d44daf.PNG)

the required system variables is ok
![4](https://cloud.githubusercontent.com/assets/20897963/20590857/8bb60658-b260-11e6-92e0-9a98c3103734.PNG)

Could you give me some suggestion? @TylerJewell 
Thanks ~

**Comment by eivantsov** [comment]
@laralijuan I am closing this one. Feel free to reopen if you face issues with launching Artik using CLI.
