### ISSUE TITLE
How to copy local file to ARTIK board?please give us some comments.

### ISSUE THREAD

**Issue by lvbin0127** [codenvy/artik#178]
![save file](https://cloud.githubusercontent.com/assets/7456723/19515440/0774773c-962a-11e6-9f64-2ae7542098f7.png)
We have two solutions, which one is better?

**Comment by eivantsov** [comment]
@lvbin0127 If you have a local file, you may upload it to the project, and it will be synced into the device to the projects replication folder.

**Comment by lvbin0127** [comment]
Sorry, it was my mistake, i want to install some rpm package from local host to ARTIK board by ARTIK IDE, so is that possible by upload rpm file to ARTIK board by ARTIK IDE and use command executer in ARTIK IDE to install rpm in ARTIK board, because if upload rpm to project, user will see this rpm file in project workspace, right?

**Comment by lvbin0127** [comment]
scp can only run on Linux system, but if user run ide in Windows, it seems impossible, how  to solve this issue?

**Comment by bmicklea** [comment]
@lvbin0127 I believe that SCP runs from our workspace (linux-based) to the device. You can use SSH to put the file into the workspace's `/projects` directory and then it will be auto-synced to the device or, if not, you can push it to the device manually.
