### ISSUE TITLE
Added sample project while creating the workspace is not appearing after the Workspace daemon is up and running

### ISSUE THREAD

**Issue by v-prabhu** [codenvy/artik#234]
Hi,
While creating the workspace, I choose to load the sample projects (ex: artik-samples). After the initialization and workspace daemon starts running, the added projects does not appear in the Project Explorer.
![added project not appearing](https://cloud.githubusercontent.com/assets/21373498/20777688/703be71e-b71d-11e6-98ea-cf6e17cc2f3e.PNG)

**Comment by eivantsov** [comment]
@v-prabhu were there any error when starting the workspace? Smth like Creating project stage never ends and you click on the workspace in the left side bar to get to the ide?

**Comment by v-prabhu** [comment]
@eivantsov during starting up the Workspace runtime (while downloading dependencies), the Internet connection got lost for some time. But later the downloading resumed and workspace daemon is up and running. After finding this issue in the workspace, I created a new workspace with the default projects again to verify. But with new workspace also the default project did not appear in project explorer.

**Comment by eivantsov** [comment]
@v-prabhu I failed to reproduce this one. 

Can you please help me a little bit and try to reproduce it with Chrome dev console on? It looks like some issues with websocket connection.

**Comment by eivantsov** [comment]
@v-prabhu to create a sample project you need Internet connection.
