### ISSUE TITLE
Sometimes Not able to delete the workspace after Workspace daemon is up and running

### ISSUE THREAD

**Issue by v-prabhu** [codenvy/artik#236]
Hi,
I have created a workspace and moved to the **Workspaces** tab. I could see the created workspace there. I check the checkbox to select the workspace and click on **Delete** button. An alert appears and I choose to click Delete again in the alert. The alert disappears but the workspace is still available. However, if I go to **Dashboard** tab and come back again to **Workspaces** tab and try to delete the selected workspace then the workspace would be deleted. 
![workspace not deleted](https://cloud.githubusercontent.com/assets/21373498/20778066/2ced0026-b720-11e6-816d-ac30e9699cde.PNG)

**Comment by eivantsov** [comment]
@v-prabhu the workspace isn't selected on your screenshot. I will take a look.

**Comment by v-prabhu** [comment]
@eivantsov I selected the workspace checkbox and clicked Delete. Once clicked on Delete button the confirmation alert, the workspace becomes unchecked(as shown in the screenshot) and not deleted too.

**Comment by eivantsov** [comment]
@v-prabhu can you repeatedly reproduce it? I have just tried deleting a running workspace and it worked for me. Tried it a couple of times.

Can you try reproducing this one with browser dev console on please?
