### ISSUE TITLE
IDE install on Mac OS X don't show ARTIK stack

### ISSUE THREAD

**Issue by bmikhael** [codenvy/artik#244]
I've installed Che IDE first then I removed Che binary under /usr/local/bin
Then, I've downloaded artik-ide binary using the following command:
`# sudo curl -sL https://raw.githubusercontent.com/codenvy/artik-ide/master/artik-ide.sh > /usr/local/bin/artik-ide`
Then I've started ARTIK IDE using the following command as mentioned in the documentation:
`# artik-ide start`
The IDE starts without showing the ARTIK stack on the dashboard!

**Comment by eivantsov** [comment]
@bmikhael you need to remove `/home/user/che` directory on your host and try it again.

**Comment by eivantsov** [comment]
Fixed by a new mechanism of launching Artik IDE and Eclipse Che.
