### ISSUE TITLE
About Unit Test for final class‘s static method in ARTIK IDE

### ISSUE THREAD

**Issue by laralijuan** [codenvy/artik#245]
Sorry for my lacking experience about Mockito's unit test.

So far, I learned it's hard to stubbing final class's static method using mockito + junit( current ARTIK IDE project adopted). 

for example, If write unit test code for plugins/plugin-artik-ide/updatesdk/[SDKInstaller.java](https://github.com/codenvy/artik-ide/blob/a9909ca3ba53d91992c8c90519b43c5363064ef4/plugins/plugin-artik-ide/src/main/java/org/eclipse/che/plugin/artik/ide/updatesdk/SDKInstaller.java) 's [getInstalledSDKVersion](https://github.com/codenvy/artik-ide/blob/a9909ca3ba53d91992c8c90519b43c5363064ef4/plugins/plugin-artik-ide/src/main/java/org/eclipse/che/plugin/artik/ide/updatesdk/SDKInstaller.java#L145) method.
how to stubbing the static [createFromAsyncRequest](https://github.com/codenvy/artik-ide/blob/a9909ca3ba53d91992c8c90519b43c5363064ef4/plugins/plugin-artik-ide/src/main/java/org/eclipse/che/plugin/artik/ide/updatesdk/SDKInstaller.java#L125) in final class？

Could you give me suggestion？ Thanks a lot.

**Comment by eivantsov** [comment]
@laralijuan currently this code cannot be tested. This PR should make it testable - https://github.com/eclipse/che/pull/3293 (it contains other changes as well, i.e. those not related to this particular piece of code)
