### ISSUE TITLE
If i want to develop some function and need to modify some Eclipse Che source code, how to build and implement on ARTIK IDE?

### ISSUE THREAD

**Issue by lvbin0127** [codenvy/artik#246]
If i want to develop some function and need to modify some Eclipse Che source code, how to build and implement on ARTIK IDE?

**Comment by eivantsov** [comment]
@lvbin0127 you will need source code for Eclipse Che. After you introduce changes there, build that module and then re-build Artik assembly.

Perhaps, if you elaborate on what you are trying to achieve I can be more helpful :)

**Comment by lvbin0127** [comment]
Thank you very much~

**Comment by eivantsov** [comment]
You need to recompile workspace api module in Che and then your Artik assembly. Please note that you will have to issue a pull request to Che. Changing workspace API is a big deal.
