### ISSUE TITLE
Create Files in particular workspace

### ISSUE THREAD

**Issue by ufgtb24yu** [codenvy/artik#253]
I want to create a file in workspace, the file works as a kind of profile, unlike code file created from users in their prject, this file is not visible for IDE users and it's created   when workspace is initialized. 
     I create it with code below, but  "Container.newFile"API blocks,  so that SUCCESS notification in the last line is not outputed.

```
  @Inject
 public EditProfilePresenter(
                                AppContext appContext,
                                NotificationManager notificationManager
                                             ){
Resource resource = appContext.getResource();//appContext is a global variable 
File newfile;
((Container) resource).newFile("myNewFile", "this is my new file").then(new Operation<File>() {
            @Override
            public void apply(File file) throws OperationException {
                newfile= file;
            }
        }).catchError(new Operation<PromiseError>() {
            @Override
            public void apply(PromiseError error) throws OperationException {
                notificationManager.notify("Failed to create resource", error.getMessage(), FAIL, FLOAT_MODE);
            }
        });
  notificationManager.notify("myNewFile already created", "", SUCCESS, FLOAT_MODE);
}
```

I wonder if my way to use the API (Container.newFile) is incorrect? If it's incorrect, then what is the proper way to create files in the root path of a workspace

**Comment by vzhukovskii** [comment]
Hello @ufgtb24yu. Client-side API doesn't support creating files in the workspace root. So the construction like `appContext.getWorkspaceRoot().newFile("name", "content").then(...)` will fails with the `java.lang.IllegalArgumentException`. 

What about `appContext.getResource()` API call. This method may return a `null` in case if there isn't any resource in the context at this moment. 

Note that each IDE part (Editor, Project Explorer) provides own selection object with currently selected resources and if you want to create a file in this way, you should check that currently selected resource is an instance of `org.eclipse.che.ide.api.resources.Container` (if folder or project is selected anywhere), or you can call `org.eclipse.che.ide.api.resources.Resource#isFolder` or `org.eclipse.che.ide.api.resources.Resource#isProject` before casting to the `org.eclipse.che.ide.api.resources.Container`.

Then. Calling `org.eclipse.che.ide.api.resources.Container#newFile` will return a Promise object which executes asynchronously, so in your case when construction `notificationManager.notify("myNewFile already created", "", SUCCESS, FLOAT_MODE);` is executing - we can't guarantee that file already created. You should process some operations with created file inside `... .then(Operation ...` callback.

**Comment by ufgtb24yu** [comment]
Thank you for the last answer , as you said, now I  try to build a project first. But it still blocks when calling createProject() and "Finish Creating" is not outputed. Could you please tell me what's the problem? Is 
dataObject set the right parameters?

```
    private Operation<Project> onComplete() {
        return new Operation<Project>() {
            public void apply(Project ignored) throws OperationException {
                notificationManager.notify("Finish create", "", SUCCESS, FLOAT_MODE);//TODO
            }
        };
    }

    private Operation<PromiseError> onFailure() {
        return new Operation<PromiseError>() {
            public void apply(PromiseError error) throws OperationException {
                notificationManager.notify("Fail to create", "", FAIL, FLOAT_MODE);//TODO
            }
        };
    }

public void createProject() {
        MutableProjectConfig dataObject=new MutableProjectConfig();
        dataObject.setName("ProfileProj");
        dataObject.setPath("mypath");
        dataObject.setType("type1");
        appContext.getWorkspaceRoot()       
                           .newProject()
                           .withBody(dataObject)
                           .send()
                           .then(onComplete())
                           .catchError(onFailure());
        notificationManager.notify("Finish Creating", "", SUCCESS, FLOAT_MODE);
}
```

**Comment by vzhukovskii** [comment]
Method `org.eclipse.che.ide.api.resources.Container#newProject` throws `java.lang.IllegalArgumentException` in case if you are trying to path an invalid parameters to the future project. Probably it is because you don't have a registered project type `type1` on the server side.

To get registered and available project types from the server, you can call rest method `org.eclipse.che.api.project.server.ProjectTypeService#getProjectTypes`:

![developer tools - http--localhost-8080-che-wksp-vd9v 2016-12-09 11-05-15](https://cloud.githubusercontent.com/assets/1968177/21043410/6eb7193e-bdff-11e6-9417-4845375a2aa5.png)

and get response with the registered project types:

![developer tools - http--localhost-8080-che-wksp-vd9v 2016-12-09 11-07-10](https://cloud.githubusercontent.com/assets/1968177/21043462/a9679ef0-bdff-11e6-8568-23043e1b1e6a.png)

as project type you should use `id` property.

**Comment by ufgtb24yu** [comment]
I excecute the URL(in my case, is explicitly like this:  http://localhost:32780/api/project-type ) in browser to access my server(already in running) , but get nothing responsed, should I just use the port 32780?

**Comment by ufgtb24yu** [comment]
Actually， my essential target is to create a new project (the reason why I need to get the valid project types), then create a file inside it, both of them should be created by code without operation through UI.  Would you please help me to check my code below, which aimed to create a project and a file in a presenter (this part needs you help), and show the file in a view .Thank you very much!!!

**Comment by ufgtb24yu** [comment]
Sorry for disturbing you again，but I meet some problem when calling http://localhost:32780/api/project-type , http-get returns no response.  
     Actually， my essential target is to create a new project (the reason why I need to get the valid project types), then create a file inside it, both of them should be created by code without operation through UI.  Would you please help me to check my code below, which aimed to create a project and a file in a presenter (this part needs you help), and show the file in a view .Thank you very much!!!

**Comment by ufgtb24yu** [comment]
Sorry for disturbing you again，but I meet some problem when calling http://localhost:32780/api/project-type , http-get returns no response.  

Actually， my essential target is to create a new project (the reason why I need to get the valid project types), then create a file inside it, both of them should be created by code without operation through UI.  Would you please help me to check my code below, which aimed to create a project and a file in a presenter (this part needs you help，the running process blocks there when creating the project), and show the file in a view .Thank you very much!!!

[EditFilePresenter.txt](https://github.com/codenvy/artik-ide/files/644621/EditFilePresenter.txt)

**Comment by eivantsov** [comment]
@ufgtb24yu port differs each time you have a running workspace. So, 32780 may not be what you actually need.

**Comment by vzhukovskii** [comment]
@ufgtb24yu take a look on this gist: https://gist.github.com/vzhukovskii/5069478068da48da73c94a7f4984711a
I've edited the initialization flow in show method.
