### ISSUE TITLE
Can you tell me how to debug ARTIK IDE project? currently we just use UI nofity to show message, it is too slow.

### ISSUE THREAD

**Issue by lvbin0127** [codenvy/artik#254]
Can you tell me how to debug ARTIK IDE project? currently we just use UI nofity to show message, it is too slow...
@laralijuan
@eivantsov

**Comment by eivantsov** [comment]
@lvbin0127 can you elaborate on what plugin you want to debug?

**Comment by lvbin0127** [comment]
Is there any different among different plugins? i want to know the detail debug procedure, i think it is no matter what's the plugin, am i right?~

**Comment by lvbin0127** [comment]
For example: plugin-artik-help.

**Comment by evoevodin** [comment]
Hi @lvbin0127, we're using [GWT](http://www.gwtproject.org/) on client side, so for debugging client extensions/plugins you have to use super-dev-mode. There is a [helpful documentation](http://www.gwtproject.org/doc/latest/tutorial/debug.html) that allows you to set up everything you need, please try it out.

**Comment by lvbin0127** [comment]
Thank you very much, and how about server side?

**Comment by eivantsov** [comment]
It depends on what service you are looking at. It may be core API provided by Che or services deployed with a workspace agent.

**Comment by evoevodin** [comment]
There are 2 possible endpoint types to debug: 
1. Artik-server(workspace master)

Export the variable `CHE_DEBUG_SERVER=true` and restart the artik server.
Then you are able to debug it as regular java remote whatever `host:port` is, e.g. by default it's _localhost:8080_

2. Workspace-agent(those server which is inside of the docker container)

You can find host and port for debugging in _machine-perspective_(The switcher in the top-right side of the IDE) sections _Servers_, it looks like this:

![image](https://cloud.githubusercontent.com/assets/4053805/21003890/64336734-bd36-11e6-94ab-09879ffa2564.png)

You can debug it like regular java remote by using host and port defined by *wsagent.debug* reference.

**Comment by lvbin0127** [comment]
I want to setup super dev mode on Intellij Idea, so i setup configuration as follow step:
1. Download gwt-2.7.0
2. Config GWT default path:
![default](https://cloud.githubusercontent.com/assets/7456723/21078722/0d2c1f64-bfb4-11e6-96cf-5dc6203a4100.png)
3. In the user guide, need to add following content in POM.xml:
<dependency>
    <groupId>com.google.gwt</groupId>
    <artifactId>gwt-dev</artifactId>
    <version>${com.google.gwt.version}</version>
</dependency>
i have check artik-ide/assembly/assembly-ide-war/pom.xml, there is already have this dependency, so i skip this step.
4. Config GWT in Intellij idea as user guide:
![default](https://cloud.githubusercontent.com/assets/7456723/21078735/83029db2-bfb4-11e6-8cb5-014f712087de.png)
5. And i setup super dev mode in Intellij idea:
![default](https://cloud.githubusercontent.com/assets/7456723/21078741/9f3b989e-bfb4-11e6-85a1-466f560fd364.png)
6. But when i run super dev mode, there are so many errors:
![default](https://cloud.githubusercontent.com/assets/7456723/21078742/b7dab902-bfb4-11e6-87ab-1dc796bfe058.png)
BTW, based on China network policy, i can not install Google software within Eclipse, so i have to use Intellij idea, so please give me some comments, thx.

**Comment by lvbin0127** [comment]
Sorry  i don't know if you can see the pictures, so i attach the file.
[Intellij Debug.zip](https://github.com/codenvy/artik-ide/files/644295/Intellij.Debug.zip)
please check.
@eivantsov

**Comment by eivantsov** [comment]
@lvbin0127 it looks like Idea cannot resolve some dependencies.

What is parent version of Che? Also, can you build artik-ide project?

**Comment by evoevodin** [comment]
It looks like super dev mod is correctly installed.

@lvbin0127 can you please do the following:
- build artik-ide `mvn clean install`
- ensure that you use native(not-bundled) maven _Settings -> Build Tools -> Maven -> Home directory_
- Reimport dependencies _Right click on the project -> Maven -> Reimport_.

**Comment by eivantsov** [comment]
Closing the issue. Feel free to reopen if the problem persists.
