### ISSUE TITLE
The installation should include TAR files for all of the images necessary to run Che for that particular version and the Che CLI

### ISSUE THREAD

**Issue by vparfonov** [codenvy/artik#264]
For  ARTIK IDE, we would include the ARTIK SDK stack image. If a user runs Che and it is not connected to the internet, it should try and use the locally saved images that were provided in the installation.

**Comment by eivantsov** [comment]
Also, the installer should untar those images when the installation is completed.

**Comment by gazarenkov** [comment]
Any estimation of the installer's size after that?

**Comment by vparfonov** [comment]
i think we need provide two version of installers offline and online, without images and with them

**Comment by TylerJewell** [comment]
1. An online installer may introduce unnecessary complexity and things would be easier to test if offline is the only supported mode.

2. The cli already generates a list of tar files to be used in a package but the list of what it produces could be improved.  

3. There is no need to inter the images during installation.  The cli uses docker to load the tar files as they are during a first boot.

**Comment by eivantsov** [comment]
@gazarenkov @vparfonov yes, two installers. With all the images, the offline installer will be up to 2GB.

**Comment by TylerJewell** [comment]
I am not comfortable with this ideas of two installers.  It significantly increases the complexity of the download page and export compliance policy that we have to consider.  There are both marketing and legal implications to such an approach.  Having a single offline-only installer simplifies things.

**Comment by eivantsov** [comment]
@TylerJewell it will be ~2GB, it that's ok, we will do it.

**Comment by TylerJewell** [comment]
Yeah, the size of the package is unavoidable - whether the customer likes it or not, if they are doing ARTIK they have to download 2GB of "stuff".  About 1.5GB of that is not related to Che - it's just their stack.  So whether they are connected for that, or its in the initial package, it's the same.

With export compliance policy, though, we have to start registering all of the software that is available for downloadable intsallation - so having offline only makes it easier to index and audit that list.
