### ISSUE TITLE
Investigate using Eclipse desktop IDE keyboard mappings for ARTIK IDE

### ISSUE THREAD

**Issue by bmicklea** [codenvy/artik#271]
There have been a few requests for the ARTIK IDE to use the same keyboard mappings as Eclipse desktop IDE. Is this possible?  I know the browser probably reserves some of those...  Will the electron client make that easier or harder?

**Comment by eivantsov** [comment]
@bmicklea should it perhaps be Eclipse Che issue?

**Comment by bmicklea** [comment]
It would require Che changes for sure but the request was from ARTIK so I
placed it here to allow it to be more easily tracked in the ARTIK backlog.
We can add a linked issue in Che repo if needed.
