### ISSUE TITLE
Add ARTIK IDE Electron client and installer CI jobs

### ISSUE THREAD

**Issue by bmicklea** [codenvy/artik#284]
The Codenvy CI systems should generate specialized packages for Artik installers and electron clients. These packages should be generated on each tagged release and made available for download.

The packages would be as outlined in the [installer spec](https://docs.google.com/document/d/1izSvR2iQSxHiYLSQqTwPsUT_3DOLJHelEPDySLmazYQ/edit#).

**Comment by vparfonov** [comment]
@bmicklea  Here we have problem with buikd client for Mac OS https://github.com/electron-userland/electron-builder/wiki/Multi-Platform-Build

**Comment by bmicklea** [comment]
Yes, I think this was expected - we will need Mac and Windows machines for
build and automated tests. They should be purchased.
