### ISSUE TITLE
Artik Electron packaging

### ISSUE THREAD

**Issue by vparfonov** [codenvy/artik#291]
1. The electron packaging should have the ARTIK IDE icon and provide minimize / maximize.
2. Connects to local ARTIK Server.

**Comment by eivantsov** [comment]
@bmicklea why do we need a system tray icon? Usually system tray icon is for utility apps and those apps that fire notifications, like slack, skype etc.

**Comment by bmicklea** [comment]
That was a requirement from Tyler for Che that I missed when copying the requirement over. Removed.
