### ISSUE TITLE
Installation of the ARTIK IDE for Windows 10 

### ISSUE THREAD

**Issue by vparfonov** [codenvy/artik#292]
- [ ] Installer: Install package (.exe) containing Docker, Electron client, Docker images for ARTIK server, ARTIK stack and utilities (https://github.com/codenvy/artik-ide/issues/264).
- [x] Installer: License display and user acceptance panel.
- [ ] Installer: Electron client install location panel - including testing if Electron can be run in a directory with spaces and, if not, trapping for that issue when selecting paths.
- [x] Installer: Docker install and version check for Docker 1.12.5+.
- [ ] Installer: Create a desktop icon for "Samsung ARTIK IDE" (the Electron client)

**Comment by vparfonov** [comment]
@bmicklea can you explain what means "ARTIK stack and utilities" ?
@slemeur we need icons for Artik IDE

**Comment by bmicklea** [comment]
It just means we have to include all the Docker images needed for ARTIK including any images needed to run the ARTIK stack (https://eclipse.org/che/docs/workspace/stacks/index.html) and any images for containers that run utilities like CLI, tests, etc... I'm not sure what's needed here so it's all stacks needed for me to install and then run the ARTIK IDE with the built-in ARTIK stack offline.

**Comment by vparfonov** [comment]
ok thx for explanation
