### ISSUE TITLE
Artik Ide is not coming up,stuck at blank screen

### ISSUE THREAD

**Issue by sivarajanennarasu** [codenvy/artik#297]
I built artik ide from source without any modification and launched it.But my browser stuck at blank screen.When I launched version field is empty.Please have a look at screen shots and kindly resolve it.
Used following cmd to launch artik-ide form built binary as follows.

        sudo docker run --rm -v /var/run/docker.sock:/var/run/docker.sock \
      -e CHE_ASSEMBLY=/home/sivarajan/artik-ide/assembly/assembly-main/target/artik-ide-1.3.1-SNAPSHOT/artik-ide-1.3.1-SNAPSHOT  eclipse/che-launcher start

![artik-ide1](https://cloud.githubusercontent.com/assets/25144843/22290135/4eb57a18-e325-11e6-8986-b71ef6c469fa.png)
![artikide2](https://cloud.githubusercontent.com/assets/25144843/22290138/504683d6-e325-11e6-98b1-8391994f4199.png)

**Comment by eivantsov** [comment]
Hello,

`che-launcher` is deprecated. Can you try the following syntax?

`docker run --rm -v /var/run/docker.sock:/var/run/docker.sock -v $path:/data -v /home/sivarajan/artik-ide:/repo codenvy/artik-cli start --debug`

`$path` is any local directory where you want to store Artik configuration files and projects.

**Comment by mutturajKaralatti** [comment]
@sivarajanennarasu  Thanks for posting this issue
@eivantsov  i am also facing the same issue. I tried with your syntax, Results are here. 


_root@alepc26:/home/alethea# 
root@alepc26:/home/alethea# docker run --rm -v /var/run/docker.sock:/var/run/docker.sock -v /home/alethea/artik_config:/data -v /home/alethea/Muttu/Jan_17/artik-ide:/repo codenvy/artik-cli start --debug
WARN: Bound 'codenvy/artik-cli' to 'codenvy/artik-cli:1.3.1'
WARNING: No swap limit support
WARN: Did not detect TTY - interactive mode disabled
INFO: (artik cli): :/repo mounted - using assembly and manifests from your local repository
INFO: (artik cli): Checking network... (hint: '--fast' skips version, network, and nightly checks)
INFO: (artik cli): Loading cli...
INFO: (artik cli): Checking registry for version '1.3.1' images
INFO: (artik download): Checking for image 'codenvy/artik-init:1.3.1'...found
INFO: (artik download): Checking for image 'codenvy/artik-server:1.3.1'...found
INFO: (artik init): Installing configuration and bootstrap variables:
INFO: (artik init):   ARTIK_HOST=10.1.1.133
INFO: (artik init):   ARTIK_VERSION=1.3.1
INFO: (artik init):   ARTIK_CONFIG=/home/alethea/artik_config
INFO: (artik init):   ARTIK_INSTANCE=/home/alethea/artik_config/instance
INFO: (artik init):   ARTIK_REPO=/home/alethea/Muttu/Jan_17/artik-ide
INFO: (artik init):   ARTIK_ASSEMBLY=/home/alethea/artik_config/instance/dev/artik-tomcat
INFO: (artik cli): Checking registry for version '1.3.1' images
INFO: (artik config): Generating artik configuration...
/repo/dockerfiles/cli/scripts/cli.sh: line 25: CHE_DEVELOPMENT_MODE: unbound variable
root@alepc26:/home/alethea# 
root@alepc26:/home/alethea#_

**Comment by sivarajanennarasu** [comment]
@eivantsov  Thanks for reply. I tried with your syntax. I am getting the following error. 

```
root@alepc022:/home/sivarajan# 
root@alepc022:/home/sivarajan# docker run --rm -v /var/run/docker.sock:/var/run/docker.sock -v /home/sivarajan/artik_config:/data -v /home/sivarajan/artik-ide:/repo codenvy/artik-cli start --debug
Unable to find image 'codenvy/artik-cli:latest' locally
latest: Pulling from codenvy/artik-cli

b7f33cc0b48e: Pull complete 
949adc96e811: Pull complete 
5feca2484c30: Pull complete 
fb2616153361: Pull complete 
b0224355881c: Pull complete 
a4d33ba99042: Pull complete 
Digest: sha256:ae427cf528f6e1379f716a6a57a02dd3acb2622d79e103f0a5234dfa8622a743
Status: Downloaded newer image for codenvy/artik-cli:latest
WARN: Bound 'codenvy/artik-cli' to 'codenvy/artik-cli:1.3.1'
WARNING: No swap limit support
WARN: Did not detect TTY - interactive mode disabled
INFO: (artik cli): :/repo mounted - using assembly and manifests from your local repository
INFO: (artik cli): Checking network... (hint: '--fast' skips version, network, and nightly checks)
INFO: (artik cli): Loading cli...
/scripts/base/library.sh: line 537: [: 10: unary operator expected
/scripts/base/library.sh: line 284: 2: unbound variable
root@alepc022:/home/sivarajan# 
root@alepc022:/home/sivarajan#
```

**Comment by eivantsov** [comment]
@sivarajanennarasu the error you have means that you have the latest Artik code but use a tagged image.

@mutturajKaralatti @sivarajanennarasu  currently, Artik IDE master is not usable. We are on it. So if you want to build smth on top of Artik IDE, use the latest tag which is `1.3.1`

**Comment by mutturajKaralatti** [comment]
@eivantsov Thanks!! Its working with tag 1.3.1
