### ISSUE TITLE
How to compile a c++ app on artik-ide

### ISSUE THREAD

**Issue by mutturajKaralatti** [codenvy/artik#307]
Hi team,

I am trying to connect RaspBerryPi to artik-ide and execute a c++ application.  I am able to execute a manually compiled binary by clicking run button on artik-ide. How can I compile the app from artik-ide. 
With my understanding there is no auto build and  **run** button process doesn't  include the compilation process.

If there is a way to compile it how can we customise the build command.

**Comment by eivantsov** [comment]
You need to select your source code file and fliw Compile button:

![build](https://cloud.githubusercontent.com/assets/5337267/22424366/06782a92-e6ff-11e6-99d9-92b195d0d0c0.png)

You can edit compilation options at Project > Edit Compilation Options

![compilation_options](https://cloud.githubusercontent.com/assets/5337267/22424444/45deb6ec-e6ff-11e6-9179-de7c5292bd38.png)

**Comment by mutturajKaralatti** [comment]
@eivantsov  Thanks for the reply!
I don't find any compile button on artik-ide. I am using tag-1.3.1.
Are you speaking about the **Execute command** button? but its disabled. 

![screenshot from 2017-01-30 18 59 12](https://cloud.githubusercontent.com/assets/24957555/22424863/7d4a1882-e71e-11e6-85ea-aeaa0637d603.png)


![screenshot from 2017-01-30 18 59 34](https://cloud.githubusercontent.com/assets/24957555/22424864/7f13ba38-e71e-11e6-94af-f559389a8973.png)

**Comment by eivantsov** [comment]
You need to select hello.cc and then Click execute command. You will see compile there

**Comment by mutturajKaralatti** [comment]
@eivantsov I tried both by selecting project as well as a specific source file. But nothing is showing up on clicking **execute command**.

![screenshot from 2017-01-30 19 03 47](https://cloud.githubusercontent.com/assets/24957555/22425455/284cc03e-e721-11e6-87a9-18cf71935464.png)

**Comment by eivantsov** [comment]
@mutturajKaralatti Rename file so that it has .cpp extension.

**Comment by mutturajKaralatti** [comment]
@eivantsov Thanks. after changing the source file extension to .cpp compilation option is available and i am able compile it. 

**Notes:**
1. It was a sample project created by artik stack on creating new workspace, so compiler option should be there for .cc file extension too.
2. Ideally the compilation option should be available for complete project in case we have the multiple source files in project. 

As i mentioned in my first comment I tried modifying the build command but modification is not taking effect. Basically its a ready only. I am unable to alter the Binary name and Compilation options.

**Comment by eivantsov** [comment]
@mutturajKaralatti bug configrmed https://github.com/codenvy/artik-ide/issues/309

**Comment by eivantsov** [comment]
Closing the issue. You may track https://github.com/codenvy/artik/issues/309
