### ISSUE TITLE
Workspace can not be deleted if the network resets (disconnects and connects again)

### ISSUE THREAD

**Issue by v-prabhu** [codenvy/artik#321]
1) Create the workspace in IDE.
2) Disconnect from the network.
3) After some times, connect the network again.
4) Click on "Workspaces" tab and delete the created workspace.
5) Workspace is not deleted.
6) User has to refresh the IDE to delete the created workspace.

If the IDE has to be refreshed to delete the workspace, then there should be an alert to the user.

**Comment by eivantsov** [comment]
I'll try to reproduce.

**Comment by eivantsov** [comment]
@v-prabhu can you reproduce it with the latest nightly image?

**Comment by v-prabhu** [comment]
@eivantsov This issue seems to be fixed with the nightly image. Thanks.
