### ISSUE TITLE
No "Connected to Artik device" alert if the connected Artik module is turned off and then turned on

### ISSUE THREAD

**Issue by v-prabhu** [codenvy/artik#322]
As a developer, I want to be alerted whenever there is a connection lost or established with the device. Currently with IDE 1.3.2 release, connection lost alert is displaying, but once connection regained the alert is not being shown.

**Comment by eivantsov** [comment]
When a connection to the device is lost, it is automatically disconnected from the IDE.

So I wonder how I can reproduce this one https://github.com/codenvy/artik-ide/issues/323

When we cannot ping Artik, the IDE disconnects it and asks a user to re-connect.

**Comment by eivantsov** [comment]
Fixed
