### ISSUE TITLE
"Updating artik sdk" alert never goes off if the connected artik device is turned off while updating the sdk

### ISSUE THREAD

**Issue by v-prabhu** [codenvy/artik#325]
1) Click "Update SDK and APIs".
2) While update in progress turn off the artik device.

"Updating artik sdk" alert never goes off.
![update sdk-device off](https://cloud.githubusercontent.com/assets/21373498/22612773/b8db1412-ea27-11e6-9307-df33c8d2dc95.PNG)

**Comment by eivantsov** [comment]
I think we will add a reasonable timeout for that.

**Comment by eivantsov** [comment]
Fixed
