### ISSUE TITLE
Alert to install development software after connecting the artik device

### ISSUE THREAD

**Issue by v-prabhu** [codenvy/artik#326]
On connecting a new artik device and connection succeeded, an alert appears to install the development software required for debugging.
![alert to install development profile](https://cloud.githubusercontent.com/assets/21373498/22612876/730ff30c-ea28-11e6-9f5f-2ff7c616ec2d.PNG)

**Comment by eivantsov** [comment]
@v-prabhu this a feature that we have implemented a few months ago.

**Comment by v-prabhu** [comment]
@eivantsov I agree with you here. But development profile is needed only for the debugging purpose. This alert makes sense if the user opts to debug the code. However, the user can connect and use the device in Production profile also. Please correct if I am wrong.

**Comment by eivantsov** [comment]
@v-prabhu no, Artik IDE features like run and debug won't work unless the device is in a dev mode.
