### ISSUE TITLE
Ambiguity between "Create Workspace" and "Add Workspace" options in Dashboard and Workspaces tab respectively

### ISSUE THREAD

**Issue by v-prabhu** [codenvy/artik#334]
I can see two options to create workspace in IDE. "Create Workspace" in Dashboard tab and "Add Workspace" in Workspaces tab. I assume, both these options are intended for the same use (Creating the new workspace). However, both these options behave differently.
1) Clicking on "Create Workspace" in Dashboard tab allows to add sample projects in the workspace.
2) Clicking on "Add Workspace" in Workspaces tab does not allow to add the sample projects or template.

Please clarify the uses of these two options if they are meant for different reasons.

**Comment by eivantsov** [comment]
Yes, Create a workspace implies creating a workspace and importing a project into it. Adding a workpace, is just workspace creation (so that you can import a project afterwards in the IDE)
