### ISSUE TITLE
[cli] Offline mode does not work

### ISSUE THREAD

**Issue by TylerJewell** [codenvy/artik#338]
The ARTIK CLI is missing files in the `/version` to be similar to how the Che CLI works.

Now, certain images are inherited from the base (good).  But the CLI needs to have two images files for each version, one for the runtime images and another for stacks.  See how Che handles it here:
https://github.com/eclipse/che/tree/master/dockerfiles/cli/version/nightly

**Comment by benoitf** [comment]
PR submitted https://github.com/codenvy/artik/issues/356
