### ISSUE TITLE
npm not getting installed while "Update SDK and APIs" 

### ISSUE THREAD

**Issue by v-prabhu** [codenvy/artik#341]
When we do "Update SDK and APIs", the npm package is not getting installed in the Artik device. I assume IDE should execute "dnf install nodejs" on Artik device to solve this.

**Comment by eivantsov** [comment]
@v-prabhu Artik SDK is compatible with a particular node.js version. It has never been in specs to install node.js on Artik boards.

**Comment by glemercier** [comment]
I confirm. Not the role of the IDE to deal with node.js versioning and installation.
