### ISSUE TITLE
"Download as zip" in Workspace toolbar option is downloading invalid/blank zip folder

### ISSUE THREAD

**Issue by v-prabhu** [codenvy/artik#359]
1) Create a workspace with some sample project.
2) Once workspace is up and running, click "Download as zip" in "Workspace" toolbar option.
3) Zip folder will be downloaded, but seems to be invalid as it can not be opened.

**Comment by eivantsov** [comment]
@v-prabhu I cannot reproduce it on Ubuntu and Win 10. What software do you use to unzip?

**Comment by eivantsov** [comment]
@v-prabhu I cannot reproduce it on Win 7 and 8 as well as Ubuntu.

**Comment by v-prabhu** [comment]
Downloaded zip folder can not be opened using windows-7/8 default unzip tool. We can extract it using 7-zip. Thanks for verifying.
