### ISSUE TITLE
Running Artik-ide on cloud and connect device to create a development environment

### ISSUE THREAD

**Issue by mutturajKaralatti** [codenvy/artik#360]
Hi team,

We are planning to launch Artik-ide on cloud and connect a device to create a development environment. 
As per my understanding this is not possible because artik-ide running on cloud(has public IP) can not reach device(private IP). 
Is there  any way to make this work.

**Comment by eivantsov** [comment]
@mutturajKaralatti yes, your device has to be reachable over a public IP
