### ISSUE TITLE
Remote access to the Artik-ide is not working

### ISSUE THREAD

**Issue by sivarajanennarasu** [codenvy/artik#361]
Artik-ide  is running on different machine, CHE_HOST_IP is exported with IP of same machine.From another machine,we were able to access arttik-ide but when we try to create the workspace we are getting following error.

We tried two options,first while lauching the artik ide we used "--remote:192.168.0.101" and second one by using env vaiable CHE_HOST_IP=192.168.0.101.The observatrion is same with both the options.

![screenshot from 2017-02-24 12_26_11](https://cloud.githubusercontent.com/assets/25144843/23294297/a9ce1e64-fa90-11e6-9013-538370ed4155.png)

**Comment by eivantsov** [comment]
@sivarajanennarasu can you elaborate on your use case?

How and where Artik IDE is started? OS? Run syntax?

**Comment by sivarajanennarasu** [comment]
**OS: Linux ubuntu 14.04 LTS.**
Machine-1 and machine-2 are on same network. Artik ide is started using the following run syntax on Machine-1. Using the http link,artik-ide opened on browser in Machine-2. 

**sudo docker run --rm -v /var/run/docker.sock:/var/run/docker.sock \
      -e CHE_ASSEMBLY=/home/sivarajan/artik-ide/assembly/assembly-main/target/artik-ide-1.3.1/artik-ide-1.3.1 \
eclipse/che-launcher start --remote: 'IP of Machine-1'**

**Comment by sivarajanennarasu** [comment]
With the same setup, following error is observed when we try to open a existing workspace.

![screenshot from 2017-02-24 15_01_51](https://cloud.githubusercontent.com/assets/25144843/23298169/9c0af970-faa2-11e6-9122-ecdd0d4dc93c.png)

**Comment by eivantsov** [comment]
docker run --rm -v /var/run/docker.sock:/var/run/docker.sock 
-e CHE_ASSEMBLY=/home/sivarajan/artik-ide/assembly/assembly-main/target/artik-ide-1.3.1/artik-ide-1.3.1 eclipse/che-launcher start --remote: 'IP of Machine-1'

You are using the wrong syntax.

`docker run -ti -v /var/run/docker.sock:/var/run/docker.sock -v /home/sivarajan/artik-ide:/repo -v /home/sivarajan/artik-data:/data -e "ARTIK_HOST=IP of Machine-1" codenvy/artik-cli:1.3.1 start`

I recommend updating to 1.4.0 though and use 1.4.0 tag (make sure you uodate your assembly to the latest version)

**Comment by sivarajanennarasu** [comment]
On upgrading to 1.4.0 reported issue is resolved.Thanks.
