### ISSUE TITLE
Mac Installer: No option to Go Online if the Wi-Fi turned off during starting IDE

### ISSUE THREAD

**Issue by v-prabhu** [codenvy/artik#367]
1) Turn off the wi-fi
2) Double click and open installed IDE. (Docker is running, Artik-IDE service is running)
3) IDE fails while verifying the "Connectivity" . Displays an error and option to change proxy and Go to offline mode.
4) Now connect the wi-fi.
5) Connectivity status does not change dynamically in the IDE. Also there is no option in the window to verify the connectivity again.
<img width="966" alt="no option to go to online" src="https://cloud.githubusercontent.com/assets/21373498/23441573/ec15f1a8-fdd7-11e6-83a6-445041678b8c.png">

**Comment by eivantsov** [comment]
Fixed in Electron client. Will be available in the next release
