### ISSUE TITLE
Cannot add the Artik device after restart workspace fails

### ISSUE THREAD

**Issue by v-prabhu** [codenvy/artik#368]
1) Start the IDE (either by installer or cloud).
2) Create a workspace with some sample project "artik-samples"
3) Once the workspace is up and running, click "Update SDK and APIs". (No need to connect the device)
4) Choose any version of the available SDK (Ex: 1.1-3)
5) After update is successful, click on "Restart Now" button in the alert.
6) This will result in an error. Click "Start" on the alert to start the workspace again.
7) Once the workspace is running, click on "Manage Artik Devices" option.
8) In "Manage Artik devices" window, there would not be "+" to add new device.
Please check the video:
**https://youtu.be/fOLqF2izPZo**

Alternatively, if the device was already added, then the devices and "-" alignment would not be proper.
<img width="1437" alt="screen shot 2017-02-28 at 2 25 35 pm" src="https://cloud.githubusercontent.com/assets/21373498/23441800/704ac092-fdd9-11e6-8485-81cc6057b55b.png">
<img width="1440" alt="devices allignment" src="https://cloud.githubusercontent.com/assets/21373498/23441805/7421d034-fdd9-11e6-9fa3-7b1e4ba0c7c2.png">

**Comment by eivantsov** [comment]
I think this one will be fixed by proper handling update sdk feature

**Comment by eivantsov** [comment]
Fixed by https://github.com/codenvy/artik/issues/302

Fix is available in nightly image
