### ISSUE TITLE
No notification to the user if the docker stops

### ISSUE THREAD

**Issue by v-prabhu** [codenvy/artik#371]
When the IDE is open and docker stops, then the user should get a notification alert to start the docker and the IDE should wait till the docker is up and running. In case of installers, on timeout, user should be given provision to restart the IDE or navigate to the "Starting IDE" (checking docker, IDE service and connectivity) screen with proper error message.

**Comment by eivantsov** [comment]
@v-prabhu this feature wasn't part of the spec. If Docker stops you should see a notification in the IDE that connection to a server is lost.

**Comment by eivantsov** [comment]
I mean if a workspace container is down, there's a notification in the IDE and a workspace stops automatically. If Docker is down, then server container is stopped as well.

**Comment by eivantsov** [comment]
OK, I have registered an issue in Eclipse Che project - https://github.com/eclipse/che/issues/4311

**Comment by eivantsov** [comment]
Closing this issue. Follow https://github.com/eclipse/che/issues/4311
