### ISSUE TITLE
Windows-8: No animation while setting up the workspace

### ISSUE THREAD

**Issue by v-prabhu** [codenvy/artik#373]
No animation while setting up the workspace on windows 8.
![no animation while setting up the workspace](https://cloud.githubusercontent.com/assets/21373498/23533237/4b120b72-ff65-11e6-965f-b456089d12cc.PNG)

**Comment by eivantsov** [comment]
@v-prabhu what animation do you expect?

**Comment by v-prabhu** [comment]
@eivantsov Find the below screenshot from Windows-7/10/Mac.
![docker stopped](https://cloud.githubusercontent.com/assets/21373498/23562452/57cf6408-fff7-11e6-8040-e73a7c02ffb6.PNG)

**Comment by eivantsov** [comment]
You must have gone through a different ws and project creation flow. Make sure you actually do the same on my systems.

**Comment by v-prabhu** [comment]
For workspace creation I followed the same flow as all other platforms. However, while creating the workspace, the animation blinks and disappears.

**Comment by eivantsov** [comment]
@v-prabhu can you record two videos showing differences in behavior?

**Comment by v-prabhu** [comment]
Windows-10: Animation while creating workspace:
https://youtu.be/kcMcLtiJXww

Windows-8: No animation while creating workspace:
https://youtu.be/3CHgL6SL4Z0

**Comment by eivantsov** [comment]
Closing as expected behavior. Crane is hidden on smaller screens.

**Comment by v-prabhu** [comment]
All the platforms has the same screen size. I am not sure why animation is hidden only on windows-8.

**Comment by eivantsov** [comment]
You can try resizing browser window on Win 7 and Mac and you will see the same result.

**Comment by v-prabhu** [comment]
Please find the video from windows-7, resizing the window and still the animation appears. Also with windows-8, the window is not resized at all. 
https://youtu.be/EySU0v4BJ2g

**Comment by eivantsov** [comment]
Try to resize it more. I see the same behavior on my laptops.

**Comment by v-prabhu** [comment]
I tried resizing more and tried all the window sizes. The issue persists only with windows-8
