### ISSUE TITLE
Workspace folder is created in IDE even if the workspace creation fails or terminated intentionally

### ISSUE THREAD

**Issue by v-prabhu** [codenvy/artik#374]
Workspace folder is created in IDE even if the workspace creation fails or terminated intentionally.
![workspace still exists if the creating project ends in error](https://cloud.githubusercontent.com/assets/21373498/23533276/822213e6-ff65-11e6-8bdd-d5a291cf27f1.PNG)

**Comment by eivantsov** [comment]
@v-prabhu I think I lack steps to reproduce, but I'd say this is expected behavior. When a workspace is created, it's projects are saved into config. And if there are no physical sources in `/projects` such a project is marked as a bad project.

**Comment by eivantsov** [comment]
Closing as expected behavior.
