### ISSUE TITLE
IDE not connecting to the intended artik device

### ISSUE THREAD

**Issue by v-prabhu** [codenvy/artik#377]
1) Create a workspace.
3) Click on "Manage Artik Devices".
2) Connect a artik device (Ex: 192.168.1.147).
4) After connection succeeds, click Disconnect in the "Manage Artik device".
5) Now change the IP address(Ex: 192.168.1.195) to connect some other device.
6) Observe that the IDE is still connects to previously connected device (192.168.1.147).

**Comment by eivantsov** [comment]
Reproduced

**Comment by v-prabhu** [comment]
The fix holds good for above mentioned scenario with nightly build (1.5.0-SNAPSHIOT). Fails in following scenario:
1) Create a workspace.
2) Connect a artik device (Ex: 192.168.1.147)
3) After connection succeeds , click disconnect in "Manage artik device".
4) Now change the IP address (Ex: 192.168.1.195) to connect to some other artik device.
5) Make sure the new artik device is not reachable over provided IP.
6) Click Connect.
7) As the device is not reachable, error displayed of ssh connection failed, as expected.
8) Observe that in the "Manage artik devices" window, the previously connected artik IP (192.168.1.147) still persists.
9) Close the "Manage Artik device" window and reopen. Observe no devices are listed.

**Comment by eivantsov** [comment]
This is expected behavior. Only a device that has been successfully connected to is saved.

**Comment by v-prabhu** [comment]
@eivantsov I think this behavior may confuse the user. Connection failed appears for the new IP where as the "Manage artik devices" window shows previously connected device. User may think that IDE is still trying to connect previous device and failing.
