### ISSUE TITLE
Sample projects added to workspace are not getting deleted

### ISSUE THREAD

**Issue by v-prabhu** [codenvy/artik#379]
1) Create a workspace with some sample projects "artik-samples".
2) Once workspace is up and running, try to delete the project from workspace.
3) Error displayed "Failed to delete artik-samples".
4) Same is true if we add "artik-blink-led","artik-nodejs-samples" or any other sample projects while creating the workspace.
![project not deleted](https://cloud.githubusercontent.com/assets/21373498/23631817/76eab9da-0274-11e7-9a79-712bfe810edb.PNG)

**Comment by eivantsov** [comment]
Related to https://github.com/codenvy/artik/issues/318

This one can be reproduced on Win 7 and 8 only.

**Comment by eivantsov** [comment]
Fixed in 1.5.0
