### ISSUE TITLE
Do not have the option to change the RUN command

### ISSUE THREAD

**Issue by v-prabhu** [codenvy/artik#380]
RUN function always uses a.out file to run the binary. I am not finding any option to change this binary file name to run. However, option to change the binary name is available for "Edit compile commands". But the specified binary would not be used while running the file, rather the linker expects a.out only.

**Comment by eivantsov** [comment]
@v-prabhu this is how it does not work (expected):

1. Compile with default settings
2. Change binary name in compilation options
3. Run.

This is how it works:

1. Compile with default settings
2. Change binary name in compilation options
3. *Re-compile*
4. Run.

Run command grabs binary name from project settings. But binary with such a name should exist.

**Comment by v-prabhu** [comment]
Thanks for the info...This works as exoected
