### ISSUE TITLE
No sample projects in IDE-1.5.0.SNAPSHOT (nightly build)

### ISSUE THREAD

**Issue by v-prabhu** [codenvy/artik#386]
I was verifying the fixes in the nightly build. I am not seeing any sample projects while creating the workspace.

**Comment by eivantsov** [comment]
This commit fixes it - https://github.com/codenvy/artik/commit/41d91296ae2211389814cb8173909622a3d71eec

You may stop Artik IDE. Then, go to your local /instance/data/stacks/stacks.json and do the same there. Then start Artik IDE.

FYI, you can still create projects when in the IDE.

I am closing this one. Feel free to reopen if tomorrow's nightly image does not fix it for you or you failed to fix it yourself in a local stacks.json.
