### ISSUE TITLE
Can not run the C file located inside the child folder of root project folder

### ISSUE THREAD

**Issue by v-prabhu** [codenvy/artik#388]
The reproducing steps are little tricky. Please follow the steps exactly mentioned below.
1) Create a workspace without any projects.
2) Once the workspace is up and running connect a artik device to IDE.
3) Click "Create Project", select "C Project" and name it "Test"
4) Project folder "Test" is created in workspace with one file "hello.c"
![capture1](https://cloud.githubusercontent.com/assets/21373498/23972641/d08970fe-098f-11e7-8553-f0aa13aad608.PNG)

5) Delete "hello.c" from the project.
![capture2](https://cloud.githubusercontent.com/assets/21373498/23972749/449e97c6-0990-11e7-9068-c6a137a9f34f.PNG)

6) Create a folder (Ex: Test-child) inside "Test" project folder.
7) Create a "C" file in "Test-child" folder. Name it anything (Ex: hello-child.c).
![capture3](https://cloud.githubusercontent.com/assets/21373498/23972798/7cdac952-0990-11e7-8c64-8f14550038c0.PNG)

8) Compile the file "hello-child.c". Binary a.out is generated.
![capture4](https://cloud.githubusercontent.com/assets/21373498/23972835/a76dcb6a-0990-11e7-8519-853e9cd82d24.PNG)

9) Now try to run the file on the connected device.
10) Always ends up with error "No binary file found. Compile your app and rerun". Observe the compiled binary is already synced with connected device.
![capture5](https://cloud.githubusercontent.com/assets/21373498/23972868/ca16b56e-0990-11e7-9727-2013b7f432d0.PNG)

![capture6](https://cloud.githubusercontent.com/assets/21373498/23972903/f14c724a-0990-11e7-8eb6-6059486eee71.PNG)

I assume, IDE tries to look for the binary within the project folder while running. In the above case binary search path differs and IDE could not find binary to run. Also, there is no provision where I can change this search path.

**Comment by eivantsov** [comment]
In this case, in compilation options, edit a.out so that it is folder/a.out

**Comment by v-prabhu** [comment]
@eivantsov This procedure is very confusing and most of the developers wound not be able to guess it by their own. **Compile-> change binary name folder/a.out->Run** . As a developer, when I compile or run any specific file then IDE should pick the binary from respective path rather than ending up with error.

**Comment by v-prabhu** [comment]
And developer would never know what has gone wrong.
